# Custom application configuration
application:
  state:
    testing: true

# Data source configuration
spring:
  datasource:
    url: jdbc:h2:file:/home/haytham/Data/h2/restfuldb
    driverClassName: org.h2.Driver
    username: haytham
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      
      
# API Documentation

#api:
#  version: 1.0
#swagger:
#  enabled: true
#  title: API Documentation
#  description: API Documentation, methods, requests and responses
#  useDefaultResponseMessages: false
#  enableUrlTemplating: false
#  deepLinking: true
#  defaultModelsExpandDepth: 1
#  defaultModelExpandDepth: 1
#  displayOperationId: false
#  displayRequestDuration: false
#  filter: false
#  maxDisplayedTags: 0
#  showExtensions: false

## Spring Security Configuration
  security:
    user:
      name: haytham
      password: toortoor
      
      
      
      
      
      
      
      
      